### ISSUE TITLE
FFMpeg hanging unless I close gui

### ISSUE THREAD

**Issue by HuyMaster** [SuperZombi/GICutscenesUI#18]
This is the error I got from the console

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "eel\__init__.py", line 303, in _process_message
KeyError: 'value'
2023-11-16T12:55:25Z <Greenlet at 0x16f1178cd00: _process_message({'return': 46.911698602582554, 'status': 'error', , <geventwebsocket.websocket.WebSocket object at 0x0)> failed with KeyError

**Comment by SuperZombi** [comment]
Describe what you did to reproduce this problem.

**Comment by HuyMaster** [comment]
https://github.com/SuperZombi/GICutscenesUI/assets/80255843/89c68f7f-fab4-47f5-9c51-b3408a9bf3d3

**Comment by HuyMaster** [comment]
Oh. It's just a fake error. However, it takes seconds to a few minutes for ffmpeg to start.

Sorry for this.

**Comment by HuyMaster** [comment]
> Describe what you did to reproduce this problem.


https://github.com/SuperZombi/GICutscenesUI/assets/80255843/e67b6954-f657-4ef6-b9a9-b97f37da2ab5

**Comment by SuperZombi** [comment]
The error was due to ffmpeg returning N/A at the beginning of the conversion. And when JS tried to set NaN value to progress bar, a hidden error occurred that was not fully displayed either in the console or in the browser.
Fix in [commit](https://github.com/SuperZombi/GICutscenesUI/commit/6b3c06e69f3433dd4669a29e52bfe532d2641254#diff-f13afd34e4e39c648101aec845146c0bd6eaebd6e40977be343180a1c748df1a).
Download latest version from [releases](https://github.com/SuperZombi/GICutscenesUI/releases) please.
